name: Build and Deploy Github&Gitee Pages

on:
  push:
    branches: [ 6.1.1 ]
    paths-ignore:
      - .gitignore
      - .editorconfig

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs pymdown-extensions

      - name: Build
        run: |
          mkdocs build -s -t readthedocs -v

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
            source-repo: "git@github.com:luizyao/pytest-chinese-doc.git"
            destination-repo: "git@gitee.com:luizyao/pytest-chinese-doc.git"

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
            gitee-username: luizyao
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            gitee-repo: luizyao/pytest-chinese-doc
            branch: 6.1.1
